# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user = User.create(:name => "lima", :dob => "02/27/1993", :location => "new york")
Post.create(:title => "Current location: Turkey", :content => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In imperdiet, justo in suscipit commodo, tortor erat pellentesque lorem, quis placerat urna ex pretium ligula. Integer consectetur eros ut nisi dapibus euismod. Etiam id libero nibh. In sit amet nunc dapibus, blandit quam id, pellentesque libero. Etiam mattis magna sit amet enim cursus viverra. Cras feugiat purus vitae ex bibendum finibus. Vestibulum tellus ipsum, ultrices vitae enim nec, dignissim consequat mi. Donec et pretium ante. Quisque sed porta tortor. Nullam eu ullamcorper massa. In hac habitasse platea dictumst. Nunc nisi quam, rhoncus vel porttitor eu, tempus ac tortor. Sed tempus, mauris eget pretium porta, erat tortor blandit risus, id pellentesque felis nibh in augue.

  Vestibulum elementum ipsum nunc, at viverra neque finibus a. Cras purus sapien, dapibus sit amet augue in, posuere consectetur purus. Fusce sagittis vel tellus eget tristique. Integer sit amet dui volutpat, ultrices nisl et, varius dolor. Phasellus eget congue urna. Mauris mi metus, tempus convallis metus efficitur, faucibus congue magna. Vivamus ornare vehicula velit, quis ornare dolor luctus quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut molestie ligula, ut aliquam sapien. Vivamus lacinia augue vitae molestie cursus. Quisque a metus quis elit ullamcorper vehicula. Vivamus viverra odio sem, in viverra leo malesuada vitae. Mauris sit amet lectus aliquet, fermentum diam vitae, tincidunt ex.

  Aenean aliquet libero urna, in finibus erat facilisis et. Vivamus consequat id nunc id finibus. Praesent molestie fringilla ex et varius. Suspendisse vel odio eu ante rutrum condimentum. Praesent lacinia vel odio id efficitur. Donec eleifend turpis id sollicitudin tempus. Nunc maximus vehicula elit, id tincidunt mauris maximus non. Curabitur in tempus nibh, ac ornare arcu. Donec dui enim, pellentesque non urna vitae, ultricies fermentum massa. Phasellus cursus commodo dictum. Nunc mattis porttitor neque, vitae pellentesque velit aliquam a.

  Duis vitae convallis sem. Suspendisse tempus imperdiet feugiat. Duis imperdiet diam nunc, sed iaculis sapien dictum non. Aliquam vel iaculis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eget nulla ultrices, pharetra felis in, gravida sem. Morbi rhoncus cursus nunc et ullamcorper. Integer a nibh justo. Sed sem nulla, euismod eget rhoncus molestie, interdum ut nunc. Integer convallis est ipsum, ornare feugiat arcu accumsan vitae.

  Proin sit amet ullamcorper elit. Vestibulum vitae facilisis metus. Cras quis facilisis lectus, aliquet mattis velit. Phasellus luctus vulputate nunc, eu commodo sapien sagittis a. Aenean sed turpis lectus. Suspendisse ultricies odio vitae arcu luctus, vel luctus lacus malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque commodo a neque sed auctor. Mauris ac lorem sed urna tristique ultricies quis a lectus. Praesent turpis ante, bibendum sed interdum in, cursus at est. In a cursus turpis, ac vulputate nunc. Aliquam ut dignissim sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;", :user => user)